version: '3.8'

services:
  mysql:
     image: mysql:8
     restart: unless-stopped
     ports:
      - 3307:3306
     volumes:
       - mysql_data:/var/lib/mysql
     command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
     ]
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: rootdb
       MYSQL_USER: rootdb
       MYSQL_PASSWORD: root123

volumes:
    mysql_data:
      driver: local